### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by epinczinger** [abredi/nextmeal#2]
- Screenshots don't work.
- Check your readme text on grammar. 
- You can add your video explanation on the readme.
- Fix Livelink before the review! 
- There should be a link somewhere to access registration.html from the website.
- On the registration form, should add a Required attribute on inputs.
- Your results list should have a link to the detail page as its says on the requirements (**- the search results page, with a list of schools each with a link to the details school page**)
- You have to share credits with the authors of the original page as it says on the requirements (**The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project**.)
You should use plain flexbox as it says on the requirements (**It's OK if you decide to use Bootstrap to build this project. But make sure that you also write some code demonstrating that you can use plain flexbox, margins and paddings out of the framework. 
The same applies to CSS grid: you can build the site with CSS grid, but be sure to use flexbox in a small part of the site.**)
- Font family? You should choose a similar to the one on the original project as it says on the requirements.
-Check Linters errors.
- .json files should be on git ignore and stay on your computer. ?

That's all I could find. Gorgeous work my friend!

**Comment by layzrd** [comment]
fixed: Thank you very much @epinczinger
